# Generated by Django 6.0 on 2026-02-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_message_sender_browser_message_sender_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reaction",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Reaksi Cepat"
            ),
        ),
    ]
