# Generated by Django 6.0 on 2026-02-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_message_reaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_disposable",
            field=models.BooleanField(default=False, verbose_name="Pesan Sekali Baca"),
        ),
    ]
